LABEL_DICT = {
    "white": 0,
    "red": 1,
    "green": 2,
    "blue": 3,
    "black": 4,
    "gold": 5,
    "colorless": 6,
    "gruul": 7, #red/green,
    "simic": 8, #green/blue,
    "golgari": 9, #black/green,
    "selesyna": 10, #green/white,
    "dimir": 11, #blue/black,
    "azorius": 12, #white/blue,
    "izzet": 13, #blue/red,
    "boros": 14, #red/white,
    "rakdos": 15, #black/red,
    "orzhov": 16, #white/black,
    "mardu": 17, #red/white/black,
    "jeskai": 18, #blue/red/white,
    "abzan": 19, #white/black/green,
    "sultai": 20, #black/green/blue,
    "temur": 21, #green/blue/red,
    "esper": 22, #white/blue/Black,
    "grixis": 23, #blue/black/red,
    "bant": 24, #green/white/blue,
    "jund": 25, #black/red/green,
    "naya": 26 #red/green/white,
}