LABEL_DICT = {
    "white": 0,
    "red": 1,
    "green": 2,
    "blue": 3,
    "black": 4,
    "gold": 5,
    "colorless": 6,
    "gruul": 7, #Red/Green,
    "simic": 8, #Green/Blue,
    "golgari": 9, #Black/Green,
    "selesyna": 10, #Green/White,
    "dimir": 11, #Blue/Black,
    "azorius": 12, #White/Blue,
    "izzet": 13, #Blue/Red,
    "boros": 14, #Red/White,
    "rakdos": 15, #Black/Red,
    "orzhov": 16, #White/Black,
    "mardu": 17, #Red/White/Black,
    "jeskai": 18, #Blue/Red/White,
    "abzan": 19, #White/Black/Green,
    "sultai": 20, #Black/Green/Blue,
    "temur": 21, #Green/Blue/Red,
    "esper": 22, #White/Blue/Black,
    "grixis": 23, #Blue/Black/Red,
    "bant": 24, #Green/White/Blue,
    "jund": 25, #Black/Red/Green,
    "naya": 26 #Red/Green/White,
}